on: push
name: Build my extension
jobs:
  buildAIX:
    name: Build AIX
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Build AIX
      uses: pavi2410/AIX-Action@master
#    - name: Create Release
#      id: create_release
#      uses: actions/create-release@v1.0.0
#      env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          draft: true
#          prerelease: false
